// <auto-generated />
using System;
using ElectronWaller.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ElectronWallet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211103071852_addedOldBalance")]
    partial class addedOldBalance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ElectronWaller.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("XDigest")
                        .HasColumnType("text")
                        .HasColumnName("x-digest");

                    b.Property<string>("XUserId")
                        .HasColumnType("text")
                        .HasColumnName("x-user_id");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            XDigest = "Y2U4YWE2YTRjYWRjYTk1YjIzZmNjY2M5NWM1MWI4NWNiODEzNDM0ZQ==",
                            XUserId = "ibrohim_ii"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = false,
                            XDigest = "NDM2YjUxNjY1ZGU0YTFkMzYwMzA0ZjRhOTRmNjM1NDkzMjc3ZWY2Nw==",
                            XUserId = "akrom_ia"
                        });
                });

            modelBuilder.Entity("ElectronWallet.Models.AccountHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("account_history");
                });

            modelBuilder.Entity("ElectronWallet.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("OldBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("old_balance");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 50000m,
                            Name = "Click.uz",
                            OldBalance = 0m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 6000m,
                            Name = "Apelsin",
                            OldBalance = 0m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ElectronWallet.Models.AccountHistory", b =>
                {
                    b.HasOne("ElectronWallet.Models.UserAccount", "AccountModel")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronWaller.Models.User", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("ElectronWallet.Models.UserAccount", b =>
                {
                    b.HasOne("ElectronWaller.Models.User", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });
#pragma warning restore 612, 618
        }
    }
}
